krafton-jungle-AI-InterviewMate/AI-InterviewMate-FE

.eslintrc.json
package.json
src/App.tsx
src/components/common/ExternalLink.tsx
src/components/layout/Nav.tsx
src/main.tsx
src/pages/Home.tsx
src/styles/GlobalStyles.tsx
yarn.lock

- 외부 링크를 걸 때 사용하는 링크 컴포넌트 추가
- 공통 네비게이션 바 구현
- 웹폰트 전역 설정
- react-icons 설치
- 공통 색상 변수 및 스타일 변수 설정
#26

chore: 공통 환경 세팅

---

src/components/layout/lobby/Room.tsx
src/pages/Home.tsx
src/pages/Lobby.tsx
src/styles/BlueBtn.tsx
src/styles/OrangeBtn.tsx
src/styles/RedBtn.tsx

- 로비 페이지 구현하는 김에 방 정보 컴포넌트도 묶어서 구현했습니다.
- 방 정보 컴포넌트에 인자값으로 API 데이터만 넘기면 화면에 표시되게 끔 구현했습니다.
- 방 목록 새로고침 버튼으로 BlueBtn 스타일 컴포넌트를 생성했습니다.
- 
- closes #31, closes #4

feat: 로비 페이지 구현 및 방 정보 요약 컴포넌트 구현

---

src/App.tsx
src/constants/pages.ts
src/pages/interview/InterviewEnd.tsx
src/pages/interview/index.tsx
src/styles/BlueBtn.tsx
src/styles/OrangeBtn.tsx
src/styles/RedBtn.tsx

- 면접 종료 페이지 라우팅
- 면접 종료 페이지 퍼블리싱
- 버튼 특이사항 발견해서 다 수정함
- closes #35

feat: 면접 종료 페이지 퍼블리싱

---

src/pages/mypage/Mypage.tsx

- 마이페이지 퍼블리싱
- 아직 구현되지 않은 페이지는 와일드카드 처리해서 404페이지로 이동하게 설정
- 면접 결과 확인페이지와 연결
- 이메일 문의시 김기태 이메일로 전송
- closes #14

feat: 마이페이지 퍼블리싱

---

src/App.tsx
src/constants/pages.ts
src/pages/mypage/Result.tsx
src/pages/mypage/ResultDetails.tsx

- 면접 결과 목록에 Link로 페이지 넘어가게 수정 
- 면접 결과 목록 상세 페이지 생성 (구현X)
- 면접 결과 목록 상세 페이지 라우팅
- App.tsx import 순서 변경
- 
- closes #21

feat: 면접 결과 목록 상세 페이지 연결

---

src/App.tsx
src/components/mypage/ResultTable/index.tsx
src/components/mypage/ResultTable/styles.ts
src/hooks/useInitializeInterviewState.ts
src/pages/interview/InterviewReady.tsx
src/pages/mypage/ResultDetails.tsx

- mui table 사용
- API 연동 필요
- #22 첫 번째 태스크

feat: 면접 결과 상세 페이지 퍼블리싱

---

src/components/interview/InterviewAiContainer/InterviewAiController/AnswerModeController.tsx
src/constants/faceLandmarkDetection.ts
src/hooks/useCheckHeadMotion.ts
src/hooks/useMotionAssessment.ts
src/lib/faceLandmarkDetection.ts
src/store/interview/selector.ts
src/types/faceLandmarkDetection.ts

1) bounding box를 벗어날 경우
2) 눈끝-귀 부근의 두 keypoints 사이의 거리가 일정 비율보다 줄어들거나 증가할 경우
위 두 가지 경우 중 한 가지 이상 해당할 경우 motion score를 감점하는 기능을 추가했습니다. (만점: 100점)
- closes #33 , closes #10

feat: head motion 채점 및 피드백 기능 추가

---

src/App.tsx
src/components/layout/common/Breadcrumbs/index.tsx
src/components/layout/common/Breadcrumbs/styles.ts
src/constants/pages.ts
src/pages/interview/InterviewReady/index.tsx
src/pages/interview/InterviewReady/style.tsx

- [QA 내용](https://www.notion.so/23-2-15-27ffb72c709743ffac4fe31576120fbb?pvs=4) 반영
- closes #66

#66 관련 작업 2

---

src/api/interview/type.ts
src/components/modal/room/AiRoomForm.tsx
src/components/modal/room/UserRoomForm.tsx

- 백엔드부분에서 API DTO 변경으로 인한 프론트 DTO 수정
- 아무튼 백엔드 때문임
- closes {issue_number}

style: 백엔드 수정으로 인한 API DTO 변경

---

src/api/questionBoxes/index.ts
src/api/questionBoxes/type.ts
src/components/mypage/questions/QuestionDialog/constants.ts
src/components/mypage/questions/QuestionDialog/index.tsx
src/components/mypage/questions/QuestionDialog/regex.ts
src/components/mypage/questions/QuestionDialog/styles.ts
src/constants/api.ts
src/constants/mypage.ts
src/hooks/queries/questionBoxes.ts
src/pages/mypage/QuestionDetails/index.tsx

- 질문 꾸러미의 질문을 추가/수정/삭제할 수 있도록 API 연동
- closes #20

feat: 질문 추가/수정/삭제 기능 연동

---

src/components/mypage/questions/QuestionDialog/index.tsx

fix: 누락된 조건식 추가

---

.vscode/settings.json
src/api/interview/type.ts
src/components/interview/userInterview/UserVideoComponent.tsx
src/components/modal/room/UserRoomForm.tsx
src/components/mypage/questions/Questions.tsx
src/pages/interview/userInterview/UserInterview.tsx
src/pages/mypage/QuestionList.tsx
yarn.lock

- 유저 면접관 기능 추가
- OpenVidu 기능 추가
- closes #7

feat: OpenVidu 적용

---

src/App.tsx
src/components/interview/InterviewAiContainer/InterviewAiController/AnswerModeController.tsx
src/components/interview/InterviewAiContainer/InterviewAiController/BreakModeController.tsx
src/components/interview/InterviewAiContainer/InterviewAiController/FinishedModeController.tsx
src/components/interview/InterviewAiContainer/InterviewAiController/QuestionModeController.tsx
src/components/interview/InterviewAiContainer/InterviewComment.tsx
src/components/interview/InterviewAiContainer/index.tsx
src/components/interview/InterviewFeedback.tsx
src/components/interview/InterviewNameTag.tsx
src/components/layout/nav/Nav.tsx
src/components/modal/room/AiRoomForm.tsx
src/components/modal/room/CreateRoom.tsx
src/components/modal/room/UserRoomForm.tsx
src/constants/interview.ts
src/hooks/useCheckAuth.ts
src/pages/Lobby.tsx
src/pages/interview/InterviewAi.tsx
src/pages/interview/InterviewReady/index.tsx
src/pages/interview/InterviewReady/style.ts
src/styles/common.ts
src/types/interview.ts

- AI 면접 대기방/진행방 UI 개선
- 비디오 컴포넌트 및 텍스트 확대
- 화면 구성 전체적으로 변경
- 공통 Nav UI 수정
- `width`: 1000px -> 1440px
- `position: fixed`
- AI 면접 단계별 페이지 라우트 가드
- 0c47293c72cbe8f796389187e05c62bc5e3b0408
- closes #87

feat: AI 면접 UI 개선

---

src/components/interview/userInterview/OvVideo.tsx
src/components/interview/userInterview/UserInterviewReady.tsx
src/components/interview/userInterview/UserVideoComponent.tsx
src/components/layout/nav/NavInterview.tsx
src/components/lobby/Room.tsx
src/components/modal/room/UserRoomForm.tsx
src/pages/interview/userInterview/UserInterview.tsx
src/pages/mypage/QuestionList.tsx
src/store/interview/atom.ts

- 유저 면접 대기방 구현
- 유저 면접 분기 처리
- 사용하지 않는 import  코드 삭제
- 면접관인지 면접자인지 구분하는 Atom 생성
- 유저 면접 대기방 컴포넌트로 분리
- 세션 구독자 배열 추가 및 삭제 코드 수정
- 면접관이 한명이라도 들어와야 시작버튼 활성화
- 면접방 인원 수 확인
- closes #98

feat: 유저 면접 대기방 구현

---

src/components/common/chartConfig.ts
src/components/layout/nav/Nav.tsx
src/components/layout/result/ResultDetailsLayout.tsx
src/components/lobby/Room.tsx
src/components/modal/room/CreateRoom.tsx
src/components/mypage/resultDetails/ResultChartAi/index.tsx
src/components/mypage/resultDetails/ResultChartUser/index.tsx
src/components/mypage/resultDetails/ResultChartUser/utils.ts
src/components/mypage/resultDetails/ResultComments/index.tsx
src/components/mypage/resultDetails/ResultTimeline/ResultTimelineItem.tsx
src/components/mypage/resultDetails/ResultTimeline/index.tsx
src/pages/mypage/ResultDetails.tsx

- aka 오답노트
- 시연용 임시 데이터로 마크업 및 스타일링만 진행
- closes #55

feat: 면접 결과 상세 페이지 - 유저 면접관

---

src/components/common/chartConfig.ts
src/components/mypage/resultDetails/ResultChartAi/generateData.ts
src/components/mypage/resultDetails/ResultChartAi/index.tsx
src/components/mypage/resultDetails/ResultChartUser/generateData.ts
src/components/mypage/resultDetails/ResultChartUser/index.tsx
src/components/mypage/resultDetails/ResultChartUser/utils.ts
src/pages/mypage/ResultDetails.tsx

- 오답노트(면접 결과 조회 상세 페이지) 대인면접/AI면접 그래프에 실제 데이터 연동하여 구현
- closes #105

feat: [오답노트] 그래프 구현

---

src/api/interview/type.ts
src/components/modal/room/AiRoomForm.tsx
src/components/modal/room/UserRoomForm.tsx
src/main.tsx
src/styles/GlobalStyles.tsx

fix: 면접 방 생성 팝업에서 MUI 컴포넌트 제거

---

src/pages/interview/InterviewAi.tsx
src/pages/interview/InterviewReady/index.tsx
src/pages/mypage/QuestionDetails/index.tsx

- 이슈 내용 및 커밋 메시지 참고
- closes #117

fix: 시나리오 시연 때 발견한 버그 수정

---

src/components/interview/InterviewAiContainer/index.tsx
src/components/mypage/questions/QuestionDialog/index.tsx
src/components/mypage/questions/QuestionDialog/styles.ts
src/components/mypage/questions/Questions.tsx
src/hooks/queries/questionBoxes.ts
src/pages/interview/InterviewAi.tsx
src/pages/mypage/QuestionDetails/index.tsx
src/pages/mypage/QuestionDetails/style.ts

feat: 질문 꾸러미, AI 면접 UI 조정

---

src/api/mypage/types.ts
src/components/interview/userInterview/IntervieweeWebcam.tsx
src/components/interview/userInterview/InterviewerQuestionTap.tsx
src/components/interview/userInterview/UserInterviewStart.tsx
src/components/interview/userInterview/UserVideoComponent.tsx
src/pages/interview/InterviewEnd.tsx
src/pages/interview/userInterview/UserInterview.tsx
src/styles/GlobalStyles.tsx

- 면접 정상 종료 시 유저 면접 면접자 face detection 결과 저장
- 면접 정상 종료 시 면접관 코멘트 저장
- 면접 중 면접관 코멘트 중간 저장
- closes #8 #101

feat: 유저 면접 결과 저장

---

src/api/mypage/types.ts
src/components/interview/InterviewAlertBox/index.tsx
src/components/interview/userInterview/IntervieweeWebcam.tsx
src/components/interview/userInterview/OvVideo.tsx
src/components/interview/userInterview/UserInterviewReady.tsx
src/components/interview/userInterview/UserInterviewStart.tsx
src/components/interview/userInterview/UserInterviewTimer.tsx
src/components/interview/userInterview/UserVideoComponent.tsx
src/components/mypage/resultDetails/ResultComments/index.tsx
src/pages/mypage/ResultDetails.tsx

- 유저 면접 면접관 결과 코멘트 추가
- 유저 면접 AI 피드백 추가
- closes #139

feat: 유저 면접 결과 코멘트 및 유저 면접 AI 피드백

---

src/components/interview/EndCommentForm.tsx
src/components/interview/SubmitProcessingPopup/index.tsx
src/components/modal/room/AiRoomForm.tsx
src/components/mypage/resultDetails/ResultTimeline/ResultTimelineItem.tsx
src/components/mypage/resultDetails/ResultTimeline/index.tsx
src/components/mypage/resultDetails/ResultTimeline/utils.ts
src/components/mypage/resultDetails/ResultVideo/Video.tsx
src/components/mypage/resultDetails/ResultVideo/index.tsx
src/hooks/queries/video.ts
src/hooks/useInitializeInterviewState.ts
src/pages/interview/InterviewEnd.tsx
src/pages/mypage/ResultDetails.tsx
src/store/interview/atom.ts

- 동영상 청크가 2개 이상일 때 api가 올바르게 호출되지 않던 이슈 처리
- 반복문에서 `useMutation`을 제대로 사용하려면 `mutate`의 콜백이 아닌 `useMutation` 자체의 콜백을 활용하는 게 좋다. `mutate`의 콜백은 경우에 따라 실행이 안 될 수 있다.
- 참고:
- https://tkdodo.eu/blog/mastering-mutations-in-react-query#some-callbacks-might-not-fire
- https://stackoverflow.com/questions/75149262/react-query-looping-through-usemutation-can-only-retrieve-the-last-request-data
- 수정 과정에서 `mutate`의 `onSuccess`의 콜백을 사용했을 때는 이 사례와 동일하게 가장 마지막의 콜백만 호출되는 문제가 있었다.
- closes #135

fix: 동영상 청크 여러 개일 때 aws api 제대로 호출되지 않던 이슈 처리

---

src/components/common/chartConfig.ts
src/components/interview/InterviewAiContainer/InterviewAiController/FinishedModeController.tsx
src/components/interview/userInterview/UserInterviewStart.tsx
src/components/modal/room/UserRoomForm.tsx
src/hooks/useInitializeInterviewState.ts
src/hooks/useRecorderPermission.ts
src/pages/interview/InterviewEnd.tsx
src/pages/interview/userInterview/UserInterview.tsx
src/store/interview/atom.ts

- 대인면접 기능에서도 녹화가 가능하도록 수정
- closes #100

feat: 유저 면접관 녹화 기능 구현

---

src/hooks/queries/mypage.ts
src/pages/interview/InterviewEnd.tsx
src/pages/interview/userInterview/UserInterview.tsx

fix: 유저 면접 로직 문제 해결

---

index.html
src/hooks/useUserRecorderPermission.ts

- @Denia-park  형기님께서 공유해주신 코드 거의 그대로 반영했고 문법만 살짝 수정했는데, 혹시 이상 없는지 한번만 확인 부탁드립니다! 감사합니다 👍🥺👍

fix: 면접관 다수일 경우에 대한 음성 합성 이슈 처리(형기님 코드 반영)

---

src/hooks/queries/interview.ts
src/pages/interview/userInterview/UserInterview.tsx

- 방이 저장되고 면접관이 남아있는 상황에 면접자가 나갈때 면접 결과가 저장이 되지 않는 이슈 처리

fix: 방이 저장되고 면접관이 남아있는 상황에 면접자가 나갈때 면접 결과가 저장이 되지 않는 이슈 처리
